model: 
    num_classes: 2
    num_filters_per_size: 256
    l2_reg_lambda: 0.0
    dropout_keep_prob: 0.5
    sequence_max_length: 280
    output: 1024
    stddev: 0.05
    adam_optimizer: 0.001
train:
    batch_size: 128
    num_epochs: 50
    evaluate_every: 5000
    checkpoint_every: 1000
misc:
    allow_soft_placement: True
    log_device_placement: False
data:
    train: valx.npy
    label: valy.npy

alphabet: abcdefghijklmnopqrstuvwxyz0123456789-,;.!?:\'\"/|_@#$%^&*~`+-=<>()[]{}
